### ISSUE TITLE
segmation fault

### ISSUE THREAD

**Issue by futureflsl** [jinbaoziyl/InsightFace_Tensorrtx#1]
environment:
ubuntu18.04
tensorrt==7.0.0.11

[100%] Linking CXX executable arcface-r50
[100%] Built target arcface-r50
(base) fut@fut-666:~/Downloads/InsightFace_Tensorrtx-master/build$ ls
arcface-r50     CMakeFiles           libmyplugins.so
CMakeCache.txt  cmake_install.cmake  Makefile
(base) fut@fut-666:~/Downloads/InsightFace_Tensorrtx-master/build$ ./arcface-r50  -s
段错误 (核心已转储)

**Comment by jinbaoziyl** [comment]
In this environment, I have not tested，but  i think You can run through with a little debugging
